### PR TITLE
Upgrade to Gnome platform version 3.36.

### PR DESCRIPTION
**Pull request by cobratbq**
Upgrade to Gnome platform 3.36.
Updated shared modules to latest version.

### CODE REVIEW

**Comment by cobratbq** [comment]
@bilelmoussaoui are you able to check why the flathub bot isn't running upon create/update of PR? Otherwise, do you know who to check this with?

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by cobratbq** [comment]
Can I and should I issues these commands myself if the bot does not act automatically?

**Comment by bilelmoussaoui** [comment]
Yes, whoever has write access can trigger a build

**Pull request merged**
